/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class fooUI extends Scene {
		public testLabel:Laya.Label;
		public long_btn:Laya.Button;
		public short_btn:Laya.Button;
		public mbox:Laya.Box;
		public mytext:laya.display.Text;
		public display_width:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("foo");
        }
    }
    REG("ui.fooUI",fooUI);
}