/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import runtime from "./runtime/runtime"
import fontTest from "./fontTest"
import myctrl from "./myctrl"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1920;
    static height:number=1080;
    static scaleMode:string="fixedauto";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="foo.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("runtime/runtime.ts",runtime);
        reg("fontTest.ts",fontTest);
        reg("myctrl.ts",myctrl);
    }
}
GameConfig.init();